version: '3.8'
services:
    oai-gnb:
        image: oaisoftwarealliance/oai-gnb:develop
        privileged: true
        container_name: rfsim5g-oai-gnb
        environment:
            RFSIMULATOR: server
            USE_ADDITIONAL_OPTIONS: -O gnb.sa.band78.106prb.rfsim.conf --parallel-config PARALLEL_SINGLE_THREAD --rfsim --phy-test
        depends_on:
            - oai-ext-dn
        networks:
            public_net:
                ipv4_address: 192.168.71.140
        volumes:
            - ./gnb.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
            - ./channelmod_rfsimu.conf:/opt/oai-gnb/etc/channelmod_rfsimu.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue:
        image: oaisoftwarealliance/oai-nr-ue:develop
        privileged: true
        container_name: rfsim5g-oai-nr-ue
        environment: 
            RFSIMULATOR: 192.168.71.140
            USE_ADDITIONAL_OPTIONS: --rfsim --phy-test --rrc_config_path .
        depends_on:
            - oai-gnb
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        volumes:
            - ./nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./channelmod_rfsimu.conf:/opt/oai-nr-ue/etc/channelmod_rfsimu.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-public"
